# This is a basic workflow that is manually triggered

name: Check Secrets

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  check-secrets:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    
    - name: Install git-secrets
      run: apt install git-secrets && git-secrets --install && git-secrets --register-aws

    - name: Look for accidentally checked-in secrets
      run: git-secrets --scan-history
